#!/bin/sh

## Variables -------------------------------#
PRIMARY="DVI-D-0"
EXTRA="DVI-D-1"
# SECONDARY="HDMI-0"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

getcolors

# - - - - - - - - -  MONITORS  - - - - - - - - -
bspc monitor $PRIMARY -d 1 2 3 4
bspc monitor $EXTRA -d 5 6 7 8
# bspc monitor $EXTRA -d 7 8 9
# bspc wm -O $PRIMARY $SECONDARY $EXTRA
bspc wm -O $PRIMARY $EXTRA

# - - - - - - - - -  BSPWM - - - - - - - - -

bspc config focused_border_color "$MAGENTA"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$FOREGROUND"
bspc config presel_feedback_color "$RED"

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config border_width            3
bspc config window_gap              8

bspc config top_padding 28
bspc config right_padding 0
bspc config bottom_padding 3
bspc config left_padding 0

bspc config split_ratio             0.50
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config merge_overlapping_monitors true

# - - - - - - - - -  RULES - - - - - - - - -
# remove all rules first
bspc rule -r *:*
bspc rule -a Opera desktop=2 follow=on focus=on
bspc rule -a opera desktop=2 follow=on focus=on
bspc rule -a Slack            desktop=5
bspc rule -a Telegram-Desktop desktop=5
bspc rule -a Telegram         desktop=5
bspc rule -a telegram         desktop=5
bspc rule -a Vlc              desktop=6
bspc rule -a Lxappearance     state=floating follow=on
bspc rule -a Pavucontrol      state=floating follow=on
bspc rule -a Nitrogen         state=floating follow=on
bspc rule -a Blueberry        state=floating follow=on
bspc rule -a Arandr           state=floating follow=on
bspc rule -a Pcmanfm          state=floating follow=on

# - - - - - - - - -  AUTOSTART - - - - - - - - -
xrandr --output DVI-D-0 --primary --mode 3440x1440 --pos 1080x91 --rotate normal \
  --output DVI-D-1 --mode 1920x1080 --pos 0x0 --rotate right &

# Kill if already running
killall -9 sxhkd \
  xsettingsd \
  dunst \
  redshift \
  picom \
  udiskie \
  greenclip \
  mpd

# Lauch notification daemon
dunst \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Fix cursor
xsetroot -cursor_name left_ptr

sxhkd &
setxkbmap "us(alt-intl)" &
nitrogen --restore &
picom --experimental-backends --config ~/.config/picom/picom.conf &
greenclip daemon &
numlockx on &
start-pulseaudio-x11 &

sleep 1s; $HOME/.bin/launch_polybar.sh &
sleep 2s; redshift -c ~/.config/redshift.conf &
sleep 3s; [ ! -s ~/.config/mpd/pid ] && mpd &
sleep 4s; udiskie -aT &
sleep 8s; xautolock -time 20 -locker 'systemctl suspend' -notify 18 -notifier "notify-send -u normal -t 10000 -- 'LOCKING screen'" &

