#!/bin/sh

## Variables -------------------------------#
PRIMARY="DVI-D-0"
EXTRA="DVI-D-1"
# EXTRA="HDMI-0"
# SECONDARY="DVI-D-1"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}

getcolors

# - - - - - - - - -  MONITORS  - - - - - - - - -
bspc monitor $PRIMARY -d 1 2 3 4
# bspc monitor $SECONDARY -d 4 5 6
bspc monitor $EXTRA -d 5 6 7 8
bspc wm -O $PRIMARY $EXTRA

# - - - - - - - - -  BSPWM - - - - - - - - -

bspc config focused_border_color "$MAGENTA"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$FOREGROUND"
bspc config presel_feedback_color "$RED"

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config border_width            3
bspc config window_gap              10

bspc config top_padding 28
bspc config right_padding 0
bspc config bottom_padding 3
bspc config left_padding 0

bspc config split_ratio             0.50
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config merge_overlapping_monitors true

# - - - - - - - - -  RULES - - - - - - - - -
# remove all rules first
bspc rule -r *:*
bspc rule -a Chromium desktop=2 follow=on focus=on
bspc rule -a chromium desktop=2 follow=on focus=on
bspc rule -a Slack            		desktop=5
bspc rule -a Spotify              desktop=6
bspc rule -a Zoom                 desktop=4
bspc rule -a Lxappearance     state=floating follow=on
bspc rule -a Pavucontrol      state=floating follow=on
bspc rule -a Nitrogen         state=floating follow=on
bspc rule -a Blueberry        state=floating follow=on
bspc rule -a Bluetooth        state=floating follow=on
bspc rule -a Arandr           state=floating follow=on

# - - - - - - - - -  AUTOSTART - - - - - - - - -

#xrandr --output DVI-D-0 --primary --mode 3440x1440 --pos 1080x126 --rotate normal --output DVI-D-1 --mode 1920x1080 --pos 0x0 --rotate right 
# xrandr --output DVI-D-0 --primary --mode 3440x1440 --pos 1920x0 --rotate normal --output DVI-D-1 --mode 1920x1080 --pos 0x427 --rotate normal

# xrandr --output DVI-D-0 --primary --mode 3440x1440 --pos 0x43 --rotate normal \
# 	--output DVI-D-1 --mode 1920x1080 --pos 3440x0 --rotate left
xrandr --output DVI-D-0 --primary --mode 3440x1440 --pos 0x0 --rotate normal \
	--output DVI-D-1 --mode 1920x1080 --pos 3440x453 --rotate normal

# Kill if already running
killall -9 sxhkd \
  xsettingsd \
  dunst \
  redshift \
  picom \
  udiskie \
  greenclip

# Lauch notification daemon
dunst \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Fix cursor
xsetroot -cursor_name left_ptr

sxhkd &
setxkbmap "us(alt-intl)" &
betterlockscreen -w &
picom --experimental-backends --config ~/.config/picom/picom.conf &
greenclip daemon &
numlockx on &
start-pulseaudio-x11 &

# sleep 9s; nvidia-settings --assign CurrentMetaMode="DY-4: vidia-auto-select @1080x1920 +3440+0 {ViewPortIn=1080x1920, ViewPortOut=1920x1080+0+0, Rotation=90,
#   ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DPY-0: vidia-auto-select @3440x1440 +0+85 {ViewPortIn=3440x1440, ViewPortOut=3440x1440+0+0,
#   ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}" &

$HOME/.bin/launch_polybar.sh &
sleep 2s; redshift -c ~/.config/redshift.conf &
# sleep 3s; [ ! -s ~/.config/mpd/pid ] && mpd &
sleep 8s; xidlehook --not-when-fullscreen --not-when-audio --timer  1200 'betterlockscreen -s' '' &
sleep 14s; udiskie -aT &
